version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: composer update && bash test/reset_tests.sh && vendor/bin/phpunit
    volumes:
      - ../:/usr/src/app

  db:
    image: mysql:8.0
    command: >
      mysqld
      --sql-mode="NO_ENGINE_SUBSTITUTION"
      --character-set-server="utf8"
      --collation-server="utf8_unicode_ci"
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test-dev
      MYSQL_PASSWORD: test-dev
      MYSQL_DATABASE: test
    volumes:
      - ./mysql/data:/var/lib/mysql
